env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  strict: off
  no-underscore-dangle: off
overrides:
  - files: tests/**/*.test.js
    plugins:
      - jest
    env:
      jest/globals: true
    extends:
      - plugin:jest/recommended
    rules:
      jest/no-done-callback: off
