version: '3'

services:
  ddb:
    image: amazon/dynamodb-local:latest
    container_name: ddb_local
    ports:
      - 8000:8000
    networks:
      - default

networks:
  default:
    name: sls-rust-network
