service: ddb
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  memorySize: 128
  architecture: arm64

plugins:
  - serverless-rust-plugin

custom:
  rust:
    cargoLambda:
      docker: false
    local:
      envFile: .env
      dockerArgs: --network sls-rust-network

functions:
  query:
    name: querySongs
    handler: ddb-local
