service: s3-local
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  memorySize: 128
  architecture: arm64

plugins:
  - serverless-rust-plugin
  - serverless-s3-local

custom:
  rust:
    cargoLambda:
      docker: false
    local:
      envFile: .env
      # Using this option, the Lambda function container can access to services running on the local machine.
      dockerArgs: --add-host host.docker.internal:host-gateway
  s3:
    address: 0.0.0.0
    directory: ./buckets
    # [[important]] Without this option, the hostname "host.docker.internal" is interpreted as a bucket name regardless of the setting.
    # For more info, see: https://github.com/jamhall/s3rver/pull/632
    vhostBuckets: false

functions:
  putS3Object:
    name: putS3Object
    handler: s3-local

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
