name: setup integration test

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        required: false
        default: 16

      node-cache-path:
        type: string
        required: false
        default: package-lock.json

      zig-version:
        type: string
        required: false
        default: 0.9.1

      cargo-path:
        type: string
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ${{ inputs.cargo-path }}

      - name: Install ZigLang
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ inputs.zig-version }}

      - name: Install Cargo Lambda
        uses: zerj9/setup-cargo-lambda@v0.1.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          cache-dependency-path: ${{ inputs.node-cache-path }}

      - name: Install Node Modules
        run: npm ci

      - name: Setup QEMU(For use arm64)
        uses: docker/setup-qemu-action@v2
