name: s3_test

on:
  push:
    branches:
      - 'fix/test-workflow'

  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Integration Test
        uses: ./.github/actions/integration_test
        with:
          cargo-path: examples/s3-local
          node-cache-path: examples/s3-local/package-lock.json

      - name: Test
        shell: bash
        run: |
          cd examples/s3-local
          ./test.sh
