name: test

on:
  push:
    branches:
      - main
      - 'release/v**'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: NPM Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Publish coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Integration Test
        uses: ./.github/workflows/integration_test
        with:
          cargo-path: tests/integration
          node-cache-path: tests/integration/package-lock.json

      - name: Test
        run: npm run test:integration
