name: test

on:
  push:
    branches:
      - main
      - 'release/v**'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: NPM Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Publish coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  integration-test:
    strategy:
      matrix:
        project:
          - simple
          - multi-binary
          - ddb-local
          - workspace
          - s3-local

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Integration Test
        uses: ./.github/actions/integration_test
        with:
          cargo-path: examples/${{ matrix.project }}
          node-cache-path: examples/${{ matrix.project }}/package-lock.json

      - name: Test
        shell: bash
        run: |
          cd examples/${{ matrix.project }}
          ./test.sh
